- name: Ensure the locale exists
  community.general.locale_gen:
    name: en_US.UTF-8
    state: present

- name: Set as default locale
  ansible.builtin.command: localectl set-locale LANG=en_US.UTF-8
